/*
CURSO: Compiladores e Intérpretes
PROYECTO #3: Análisis Semántico
ESTUDIANTES: Sebastián Sandí Blanco y Melany Bustos Cerdas
ARCHIVO: parser.cup

OBJETIVO: Definir la gramática del lenguaje, realizar la estructura para el árbol sintáctico y la tabla de símbolos

ENTRADA: Especificaciones de terminales, no terminales, precedencias, nodos y la gramática del lenguaje

SALIDA: Clase java con constantes enteras que representan cada token y analizador sintáctico generado con CUP que construye el árbol
sintáctico y la tabla de símbolos.

RESTRICCIONES:
-La validación semántica se limita a errores básicos.

Código obtenido de la página oficial de Cup y adaptado para el proyecto
https://www2.cs.tum.edu/projects/cup/ */

package generados;
import java_cup.runtime.*;
import src.Nodo;
import src.TipoNodo;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.LinkedHashMap;

parser code {:

    public boolean errorDetectado = false; //esto es para indicar si la estructura es válida o no

    public void errorEnGramatica(Symbol s) {
            errorDetectado = true;
            System.err.println("Error sintáctico: Token inesperado '" + s.value +
                               "' en la línea " + (s.left + 1) + ", columna " + (s.right + 1));
    }

    public void imprimirTablaSimbolos() {
        action_obj.imprimirTablaSimbolos();
    }

    public void imprimirErrores() {
            action_obj.imprimirErrores();
    }
:};

action code {:
    LinkedHashMap<String, ArrayList<String>> tablaSimbolos = new LinkedHashMap<>();
    ArrayList<String> erroresTablaSimbolos = new ArrayList<>();


    String scopeActual = "GLOBAL";
    int contadorBloques = 0;
    int contadorFor = 0;
    int contadorLoop = 0;
    int contadorDecide = 0;


    HashMap<String, String> raizScope = new HashMap<>();
    HashMap<String, String> nombreParaScope = new HashMap<>();


    {
        tablaSimbolos.put("GLOBAL", new ArrayList<>());
        raizScope.put("GLOBAL", null);
        nombreParaScope.put("GLOBAL", "GLOBAL");
    }


    void entrarFuncion() {
        contadorBloques = 0;
        contadorFor = 0;
        contadorLoop = 0;
        contadorDecide = 0;
        if(scopeActual == null) scopeActual = "GLOBAL";
    }

    void agregarFuncion(String nombre, String tipo) {

        agregarSimbolo(nombre, tipo + " (función)");
        String funcScope = scopeActual + "." + nombre;
        raizScope.put(funcScope, scopeActual);
        tablaSimbolos.put(funcScope, new ArrayList<>());
        nombreParaScope.put(funcScope, nombre);
        scopeActual = funcScope;
    }


    void entrarBloque(String tipoBloque) {
        String nombreBloque = tipoBloque;
        switch(tipoBloque) {
            case "for": contadorFor++; nombreBloque += contadorFor; break;
            case "loop": contadorLoop++; nombreBloque += contadorLoop; break;
            case "decide": contadorDecide++; nombreBloque += contadorDecide; break;
            case "bloque": contadorBloques++; nombreBloque += contadorBloques; break;
        }
        String nuevoScope = scopeActual + "." + nombreBloque;
        raizScope.put(nuevoScope, scopeActual);
        scopeActual = nuevoScope;
        tablaSimbolos.put(scopeActual, new ArrayList<>());
        nombreParaScope.put(scopeActual, nombreBloque);
    }

    void salirBloque() {
        String padre = raizScope.get(scopeActual);
        if (padre != null) {
            scopeActual = padre;
        }
    }


    void agregarSimbolo(String nombre, String tipo) {
        ArrayList<String> tabla = tablaSimbolos.get(scopeActual);
        if (tabla != null) {
            for (String entrada : tabla) {
                if (entrada.startsWith(nombre + ":")) {
                    erroresTablaSimbolos.add(
                        "Error: La variable '" + nombre + "' ya existe en el ámbito " + scopeActual
                    );
                    return;
                }
            }
            tabla.add(nombre + ":" + tipo);
        }
    }


    public void imprimirTablaSimbolos() {
        System.out.println("\n  TABLA DE SÍMBOLOS  ");
        for (String scope : tablaSimbolos.keySet()) {
            String mostrarScope;
            if (scope.equals("GLOBAL")) {
                mostrarScope = "GLOBAL";
            } else {
                mostrarScope = scope.replace(".", ".");
            }
            System.out.println("\nScope: " + mostrarScope);
            ArrayList<String> tabla = tablaSimbolos.get(scope);
            if (tabla.isEmpty()) {
                System.out.println("  (ninguna declaración)");
            } else {
                for (String s : tabla) {
                    System.out.println("  " + s);
                }
            }
        }
    }

    public void imprimirErrores() {
        for (String err : erroresTablaSimbolos) {
            System.err.println(err);
        }
    }

:}

/* Palabras reservadas */
terminal String WORLD;     // world
terminal String LOCAL;     // local
terminal String GIFT;      // gift
terminal String RETURN;    // return
terminal String BREAK;     // break

terminal String DECIDE;    // decide
terminal String OF;        // of
terminal String ELSE;      // else
terminal String END;       // end
terminal String LOOP;      // loop
terminal String EXIT;      // exit
terminal String WHEN;      // when
terminal String FOR;       // for

terminal String SHOW;      // show
terminal String GET;       // get
terminal String NAVIDAD;   // navidad (main)

/* Tipos de datos */
terminal String INT;       // int
terminal String FLOAT;     // float
terminal String BOOL;      // bool
terminal String CHAR;      // char
terminal String STRING;    // string
terminal String COAL;      // coal (tipo del main)

/* Operadores */
terminal String PLUS;      // +
terminal String MINUS;     // -
terminal String MULT;      // *
terminal String DIV;       // /
terminal String DIVENT;    // //
terminal String MOD;       // %
terminal String ELEV;      // ^


terminal String INC;       // ++
terminal String DEC;       // --

terminal String LOWTHAN;        // <
terminal String LOWEQ;        // <=
terminal String GTHAN;        // >
terminal String GEQ;        // >=
terminal String EQ;        // ==
terminal String NEQ;        // !=

terminal String AND;       // @
terminal String OR;        // ~
terminal String NOT;       // Σ
terminal String ARROW;

/* Caracteres del lenguaje */
terminal String ASSIGN;    // =
terminal String LBRACE;    // ¡
terminal String RBRACE;    // !
terminal String LPAREN;    // ¿
terminal String RPAREN;    // ?
terminal String LBRACKET; // [
terminal String RBRACKET; // ]
terminal String COMMA;     // ,
terminal String ENDL;      // endl

/* Literales */
terminal Integer   INT_LITERAL;
terminal Double    FLOAT_LITERAL;
terminal String    STRING_LITERAL;
terminal Character CHAR_LITERAL;
terminal Boolean   BOOL_LITERAL;

/* Identificador */
terminal String ID; // nombres de variables y funciones

/* No terminales con tipos definidos */
non terminal Nodo programa, operadorRelacional, declaracionesYFuncionesGlobales, elementoGlobal, declaracionGlobal, listaFunciones, funcion, funcionMain, parametros, listaParametros, bloque, listaSentencias,
sentencia, declaracionLocal, declaracionArreglo, arregloAsignacion, listaFilas, fila, listaValores, valoresArreglo, sentenciaMostrar, sentenciaLeer,
sentenciaReturn, sentenciaBreak, sentenciaDecide, casosDecide, casoDecide, casoElse, sentenciaLoop, salidaLoop, sentenciaFor, forIniciar, forActualizar,
llamadaFuncion, argumentos, listaArgumentos, expresion, terminoLogico, factorLogico, expresionRelacional, expresionAritmetica, termino, factor, primario, literal, declaracion, declaracionVariable;
non terminal String tipo;

/* Precedencias */
precedence left OR;
precedence left AND;
precedence right NOT;
precedence left EQ, NEQ, LOWTHAN, LOWEQ, GTHAN, GEQ;
precedence left PLUS, MINUS;
precedence left MULT, DIV, DIVENT, MOD;
precedence right ELEV;


start with programa;

programa ::= declaracionesYFuncionesGlobales:dfg funcionMain:m
    {:
        Nodo raiz = new Nodo("PROGRAMA");
        if(dfg != null) raiz.agregarHijo(dfg);
        if(m != null) raiz.agregarHijo(m);

        if(parser.errorDetectado) {
                    System.out.println("\n[ERROR] Estructura NO válida según la gramática.");
                } else {
                    System.out.println("\n[ÉXITO] Estructura válida según la gramática.");
                }
        RESULT = raiz;
    :}
;


declaracionesYFuncionesGlobales::=declaracionesYFuncionesGlobales:dfg elementoGlobal:eg

    {:
        dfg.agregarHijo(eg);
        RESULT = dfg;
    :}
    | /* caso base vacío */
    {: RESULT = new Nodo("DECLARACIONES GLOBALES Y FUNCIONES"); :}
;

elementoGlobal ::=
      declaracionGlobal:d
      {: RESULT = d; :}
    | funcion:f
      {: RESULT = f; :}
;


declaracionGlobal ::= WORLD tipo:t ID:i ENDL {:
  scopeActual = "GLOBAL";
  agregarSimbolo(i, t);

  Nodo identificador = new Nodo(i);
  Nodo tipo = new Nodo(t, TipoNodo.TIPO);
  Nodo declaracionG = new Nodo("Declaración global");

  //agregar como hijos
  tipo.agregarHijo(identificador);
  declaracionG.agregarHijo(tipo);
  RESULT = declaracionG;

:}
        //Declaración con asignación
		    | WORLD tipo:t ID:i ASSIGN expresion:e ENDL {:
		    //Tabla de símbolos
        scopeActual = "GLOBAL";
        agregarSimbolo(i, t);
        //Árbol sintáctico
		    Nodo declaracionG = new Nodo("Declaración global con asignación: " + t + " " + i );
		    Nodo assign = new Nodo("=", TipoNodo.ASIGNACION);
		    assign.agregarHijo(new Nodo(i.toString(), TipoNodo.VARIABLE));
		    assign.agregarHijo(e);
		    declaracionG.agregarHijo(assign);
		    RESULT = declaracionG;
        :} //Manejo de errores
        | WORLD error ENDL {:
            parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR EN DECLARACIÓN GLOBAL <<<");
        :}

;


tipo ::= INT     {: RESULT = "int"; :}
       | FLOAT   {: RESULT = "float"; :}
       | BOOL    {: RESULT = "bool"; :}
       | CHAR    {: RESULT = "char"; :}
       | STRING  {: RESULT = "string"; :}
;

funcion ::= GIFT tipo:t ID:i
    {:
        entrarFuncion();
        agregarFuncion(i,t);
    :}
    LPAREN parametros:p RPAREN bloque:b
    {:
        //El nombre de la función como un nodo aparte
        Nodo nombreFuncion = new Nodo(i, TipoNodo.FUNCION);
        nombreFuncion.agregarHijo(p);
        nombreFuncion.agregarHijo(b);
        //Nodo padre
        Nodo funcion = new Nodo("Función");
        funcion.agregarHijo(nombreFuncion);
        scopeActual = raizScope.get(scopeActual);
        RESULT = funcion;
    :}
    | error RBRACE {:
            parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR EN ESTRUCTURA DE FUNCIÓN <<<");
          :}
;

funcionMain ::= COAL NAVIDAD LPAREN RPAREN
    {:
        entrarFuncion();
        agregarFuncion("navidad","coal");

    :}
    bloque:b
    {:
        Nodo funcionMain = new Nodo("Función Main");
        funcionMain.agregarHijo(b);
        scopeActual = raizScope.get(scopeActual);
        RESULT = funcionMain;
    :}
    | error {:
            parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR CRÍTICO EN FUNCIÓN MAIN <<<");
        :};


parametros ::= {:
    RESULT = new Nodo("Lista de parámetros vacía");
:}
| listaParametros:lp {:
    RESULT = lp;
:};

listaParametros ::= tipo:t ID:i {:
    agregarSimbolo(i, t);
    Nodo contenedor = new Nodo("Parámetros", TipoNodo.PARAMETROS);
    contenedor.agregarHijo(new Nodo(i));
    RESULT = contenedor;
:}
| listaParametros:lp COMMA tipo:t ID:i {:
    agregarSimbolo(i, t);
    lp.agregarHijo(new Nodo(i));
    RESULT = lp;
:}
| error COMMA tipo ID {:
    parser.errorDetectado = true;
    RESULT = new Nodo(">>> ERROR: PARÁMETRO NO VÁLIDO <<<");
:};


bloque ::= LBRACE {:
        entrarBloque("bloque");  // entra a bloque local
    :}
    listaSentencias:ls RBRACE {:
    Nodo bloque = new Nodo("Bloque");
    bloque.agregarHijo(ls);
    salirBloque();
    RESULT = bloque;
:};

listaSentencias ::= listaSentencias:ls sentencia:s
    {:
        ls.agregarHijo(s);
        RESULT = ls;
    :}
    | /* caso base vacío */
    {: RESULT = new Nodo("LISTA SENTENCIAS"); :}
;

sentencia ::= ID:i ASSIGN expresion:e ENDL
              {:
                Nodo n = new Nodo("Asignación " + i);
                n.agregarHijo(e);
                RESULT = n;
              :}
             | ID:i LBRACKET expresion:e1 RBRACKET
                  LBRACKET expresion:e2 RBRACKET
                  ASSIGN expresion:e3 ENDL
              {:
                Nodo n = new Nodo("Asignación Arreglo " + i);
                n.agregarHijo(e1);
                n.agregarHijo(e2);
                n.agregarHijo(e3);
                RESULT = n;
              :}
	    | declaracionLocal:s    {: RESULT = s; :}
            | declaracionArreglo:s  {: RESULT = s; :}
            | expresion:e ENDL      {:
                Nodo sent = new Nodo("Sentencia Expresión");
                sent.agregarHijo(e);
                RESULT = sent;
              :}
            | error ENDL
                          {:
                            Nodo errorNodo = new Nodo(">>> ERROR SINTÁCTICO <<< ");
                            parser.errorDetectado = true;
                            RESULT = errorNodo;
                          :}
            | sentenciaMostrar:s    {: RESULT = s; :}
            | sentenciaLeer:s       {: RESULT = s; :}
            | sentenciaReturn:s     {: RESULT = s; :}
            | sentenciaBreak:s      {: RESULT = s; :}
            | sentenciaDecide:s     {: RESULT = s; :}
            | sentenciaLoop:s       {: RESULT = s; :}
            | sentenciaFor:s        {: RESULT = s; :}

;

declaracionLocal ::=
    LOCAL declaracion:d
    {:
        Nodo n = new Nodo("Declaración local");
        n.agregarHijo(d);
        RESULT = n;
    :}
    | LOCAL error
                  {:
                    Nodo errorNodo = new Nodo(">>> ERROR DECLARANDO VARIABLE LOCAL <<< ");
                    parser.errorDetectado = true;
                    RESULT = errorNodo;
                  :}
;

declaracion ::=
      declaracionVariable:dv
      {: RESULT = dv; :}
    | declaracionArreglo:da
      {: RESULT = da; :}

;

declaracionVariable ::=
      tipo:t ID:i ENDL
      {:
          agregarSimbolo(i, t);

          Nodo identificador = new Nodo(i);
          Nodo tipo = new Nodo(t, TipoNodo.TIPO);
          Nodo declaracionLocal = new Nodo("Declaración de variable sin asignación");

          //agregar como hijos
          tipo.agregarHijo(identificador);
          declaracionLocal.agregarHijo(tipo);
          RESULT = declaracionLocal;

      :}
      | tipo:t ID:i ASSIGN expresion:e ENDL
        {:
            agregarSimbolo(i, t);
            Nodo declaracionLocal = new Nodo("Declaración de variable con asignación: " + t + " " + i );
            Nodo assign = new Nodo("=", TipoNodo.ASIGNACION);
            assign.agregarHijo(new Nodo(i.toString(), TipoNodo.VARIABLE));
            assign.agregarHijo(e);
            declaracionLocal.agregarHijo(assign);
            RESULT = declaracionLocal;

        :}
      | ID ENDL
                   {:
                     Nodo errorNodo = new Nodo(">>> ERROR, DEBE ASIGNAR UN TIPO AL IDENTIFICADOR <<< ");
                     parser.errorDetectado = true;
                     RESULT = errorNodo;
                   :}
;

declaracionArreglo ::= tipo:t ID:i LBRACKET INT_LITERAL RBRACKET LBRACKET INT_LITERAL RBRACKET ENDL {:
                         agregarSimbolo(i, t + "[ ][ ]");
                        RESULT = new Nodo("Declaración arreglo bidimensional: " + i + " " + t + "[ ][ ]");
:}
   | tipo:t ID:i LBRACKET INT_LITERAL RBRACKET LBRACKET INT_LITERAL RBRACKET ASSIGN arregloAsignacion:a ENDL {:
      agregarSimbolo(i, t + "[ ][ ]");
      Nodo n = new Nodo("Declaración de arreglo con asignación " + i + " " + t + "[ ][ ]");
      n.agregarHijo(a);
      RESULT = n;
:}
;

arregloAsignacion ::= LBRACE listaFilas:lf RBRACE {:
                        Nodo n = new Nodo("Valores Arreglo");
                        n.agregarHijo(lf);
                        RESULT = n;
                    :}
;

listaFilas ::= fila:f {:
                Nodo n = new Nodo("Lista de Filas");
                n.agregarHijo(f);
                RESULT = n;
              :}
             | listaFilas:lf COMMA fila:f {:
                lf.agregarHijo(f);
                RESULT = lf;
              :}
;

fila ::= LBRACE listaValores:lv RBRACE {:
            Nodo n = new Nodo("Fila");
            n.agregarHijo(lv);
            RESULT = n;
         :}
;

listaValores ::= valoresArreglo:v {:
                    Nodo n = new Nodo("Lista de Valores");
                    n.agregarHijo(v);
                    RESULT = n;
                 :}
               | listaValores:lv COMMA valoresArreglo:v {:
                    lv.agregarHijo(v);
                    RESULT = lv;
                 :}
;

valoresArreglo ::= INT_LITERAL:i  {: RESULT = new Nodo(i.toString()); :}
                 | CHAR_LITERAL:c {: RESULT = new Nodo(c.toString()); :}
;

sentenciaMostrar ::= SHOW expresion:e ENDL {:
                        Nodo n = new Nodo("Sentencia Show");
                        n.agregarHijo(e);
                        RESULT = n;
                    :}
;

sentenciaLeer ::= GET ID ENDL {: RESULT = new Nodo("Sentencia Get"); :}
;

sentenciaDecide ::= DECIDE OF {:
                  entrarBloque("decide");:}
                  casosDecide:cd casoElse:ce END DECIDE ENDL {:
                  Nodo n = new Nodo("IF", TipoNodo.IF);
                  n.agregarHijo(cd);
                  n.agregarHijo(ce);
                  salirBloque();
                  RESULT = n;
                    :}
;

casosDecide ::= casoDecide:c {:
                    Nodo n = new Nodo("Casos Decide");
                    n.agregarHijo(c);
                    RESULT = n;
                :}
              | casosDecide:cd casoDecide:c {:
                    cd.agregarHijo(c);
                    RESULT = cd;
                :}
;

casoDecide ::= expresion:e ARROW bloque:b {:
                Nodo n = new Nodo("Caso", TipoNodo.CASO);
                n.agregarHijo(e);
                n.agregarHijo(b);
                RESULT = n;
              :}
              |
              LPAREN error RPAREN ARROW bloque:b
                  {:
                      parser.errorDetectado = true;
                      Nodo n = new Nodo("CASO (ERROR EN CONDICIÓN)");
                      n.agregarHijo(b); // se rescata el cuerpo del bloque
                      RESULT = n;
                  :}
;

casoElse ::= {: RESULT = new Nodo("Sin caso Else", TipoNodo.NO_ELSE); :}
           | ELSE ARROW bloque:b {:
                Nodo n = new Nodo("Caso Else", TipoNodo.CASO_ELSE);
                n.agregarHijo(b);
                RESULT = n;
             :}
;

sentenciaLoop ::= LOOP {:
                entrarBloque("loop");:}
                listaSentencias:ls salidaLoop:sl END LOOP ENDL {:
                    Nodo n = new Nodo("LOOP", TipoNodo.LOOP);
                    n.agregarHijo(ls);
                    n.agregarHijo(sl);
                    salirBloque();
                    RESULT = n;
                  :}
;

salidaLoop ::= EXIT WHEN expresion:e ENDL {:
                Nodo n = new Nodo("Salida Loop");
                n.agregarHijo(e);
                RESULT = n;
              :}
        | EXIT WHEN error ENDL {:
            parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR EN LA DECLARACIÓN PARA CERRAR EL CICLO <<<");
        :}
;

sentenciaFor ::= FOR LPAREN {:
               entrarBloque("for");:}
               forIniciar:fi ENDL expresion:e ENDL forActualizar:fa RPAREN bloque:b {:

               Nodo n = new Nodo("FOR", TipoNodo.FOR);
               n.agregarHijo(fi);
               n.agregarHijo(e);
               n.agregarHijo(fa);
               n.agregarHijo(b);
               salirBloque();
               RESULT = n;
:}
;


forIniciar ::= tipo:t ID:i ASSIGN expresion:e
      {:
          agregarSimbolo(i, t);
          Nodo n = new Nodo("Valor inicial del for");
          Nodo asignacion = new Nodo("=", TipoNodo.ASIGNACION);
          Nodo identificador = new Nodo(i.toString(),TipoNodo.VARIABLE);

          asignacion.agregarHijo(identificador);
          asignacion.agregarHijo(e);

          n.agregarHijo(asignacion);
          RESULT = n;
      :}
    | ID:i ASSIGN expresion:e
      {:
          Nodo n = new Nodo("Valor inicial del for");
          Nodo asignacion = new Nodo("=", TipoNodo.ASIGNACION);
          Nodo identificador = new Nodo(i.toString());

          asignacion.agregarHijo(identificador);
          asignacion.agregarHijo(e);

          n.agregarHijo(asignacion);
          RESULT = n;
      :}
;


forActualizar ::=  INC ID:i
      {:
          Nodo n = new Nodo("Actualización del for");
          Nodo asignacion = new Nodo("=", TipoNodo.ASIGNACION);
          Nodo id = new Nodo(i, TipoNodo.VARIABLE);
          Nodo incremento = new Nodo("+", TipoNodo.ASIGNACION); //i = i + 1
          Nodo idIncremento = new Nodo(i, TipoNodo.VARIABLE);
          Nodo incrementoDeUno = new Nodo("1", TipoNodo.CONSTANTE);

          incremento.agregarHijo(idIncremento);
          incremento.agregarHijo(incrementoDeUno);
          asignacion.agregarHijo(id);
          asignacion.agregarHijo(incremento);

          n.agregarHijo(asignacion);


          RESULT = n;
      :}
    | DEC ID:i
      {:
          Nodo n = new Nodo("For Actualización (-- )");
          n.agregarHijo(new Nodo("Variable: " + i));
          RESULT = n;
      :}
;

sentenciaReturn ::= RETURN expresion:e ENDL {:
                        Nodo n = new Nodo("Sentencia Return");
                        n.agregarHijo(e);
                        RESULT = n;
                    :}
;

sentenciaBreak ::= BREAK ENDL {: RESULT = new Nodo("Sentencia Break"); :}
;

llamadaFuncion ::= ID LPAREN argumentos:a RPAREN {:
                    Nodo n = new Nodo("Llamada a Función");
                    n.agregarHijo(a);
                    RESULT = n;
                  :}
;

argumentos ::= {: RESULT = new Nodo("Sin argumentos"); :}
             | listaArgumentos:la {: RESULT = la; :}
;

listaArgumentos ::= expresion:e {:
                        Nodo n = new Nodo("Lista de Argumentos");
                        n.agregarHijo(e);
                        RESULT = n;
                    :}
                  | listaArgumentos:la COMMA expresion:e {:
                        la.agregarHijo(e);
                        RESULT = la;
                    :}
;

expresion ::= expresion:e OR terminoLogico:t {:
                        Nodo n = new Nodo("OR", TipoNodo.OPERADOR);
                        n.agregarHijo(e);
                        n.agregarHijo(t);
                        RESULT = n;
                    :}
                  | terminoLogico:t {:
                  RESULT = t; :}
;

terminoLogico ::= terminoLogico:t AND factorLogico:f {:
                    Nodo n = new Nodo("AND", TipoNodo.OPERADOR);
                    n.agregarHijo(t);
                    n.agregarHijo(f);
                    RESULT = n;
                  :}
                | factorLogico:f {:
                    RESULT = f; :}
;

factorLogico ::= NOT factorLogico:f {:
                    Nodo n = new Nodo("Negación Lógica", TipoNodo.NEGACION);
                    n.agregarHijo(f);
                    RESULT = n;
                 :}
               | expresionRelacional:e {:
                   RESULT = e; :}
;

expresionRelacional ::= expresionAritmetica:e1 operadorRelacional:o expresionAritmetica:e2 {:
                            Nodo n = new Nodo("Expresión Relacional");
                            o.agregarHijo(e1); //agregar al operador relacional su argumento izquierdo
                            o.agregarHijo(e2); //agregar al operador relacional su argumento derecho
                            n.agregarHijo(o);
                            RESULT = n;
                        :}
                      | expresionAritmetica:e {:
                            RESULT = e; :}
;

operadorRelacional ::=
      LOWTHAN {: RESULT = new Nodo("<", TipoNodo.OPERADOR);  :}
    | LOWEQ   {: RESULT = new Nodo("<=", TipoNodo.OPERADOR); :}
    | GTHAN   {: RESULT = new Nodo(">", TipoNodo.OPERADOR);  :}
    | GEQ     {: RESULT = new Nodo(">=", TipoNodo.OPERADOR); :}
    | EQ      {: RESULT = new Nodo("==", TipoNodo.OPERADOR); :}
    | NEQ     {: RESULT = new Nodo("!=", TipoNodo.OPERADOR); :}
;

expresionAritmetica ::= expresionAritmetica:e PLUS termino:t {:
                            Nodo n = new Nodo("+", TipoNodo.OPERADOR);
                            n.agregarHijo(e);
                            n.agregarHijo(t);
                            RESULT = n;
                        :}
                      | expresionAritmetica:e MINUS termino:t {:
                            Nodo n = new Nodo("-", TipoNodo.OPERADOR);
                            n.agregarHijo(e);
                            n.agregarHijo(t);
                            RESULT = n;
                        :}
                      | termino:t {: RESULT = t; :}
;

termino ::= termino:t MULT factor:f {:
                Nodo n = new Nodo("*", TipoNodo.OPERADOR);
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t DIV factor:f {:
                Nodo n = new Nodo("/", TipoNodo.OPERADOR);
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t DIVENT factor:f {:
                Nodo n = new Nodo("//", TipoNodo.OPERADOR);
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t MOD factor:f {:
                Nodo n = new Nodo("%", TipoNodo.OPERADOR);
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | factor:f {: RESULT = f; :}
;

factor ::= factor:f ELEV primario:p {:
            Nodo n = new Nodo("^", TipoNodo.OPERADOR);
            n.agregarHijo(f);
            n.agregarHijo(p);
            RESULT = n;
          :}
         | primario:p {: RESULT = p; :}
;


primario ::= ID:v {: RESULT = new Nodo(v.toString(), TipoNodo.VARIABLE); :}
           | literal:l {: RESULT = l; :}
           | llamadaFuncion:lf {: RESULT = lf; :}
           | ID LBRACKET expresion:e1 RBRACKET LBRACKET expresion:e2 RBRACKET {:
                Nodo n = new Nodo("Acceso Arreglo");
                n.agregarHijo(e1);
                n.agregarHijo(e2);
                RESULT = n;
             :}
           | LPAREN expresion:e RPAREN {: RESULT = e; :}
;

literal ::=
      MINUS INT_LITERAL:v {: RESULT = new Nodo("-" + v, TipoNodo.CONSTANTE); :}
    | MINUS FLOAT_LITERAL:v {: RESULT = new Nodo("-" + v, TipoNodo.CONSTANTE); :}
    | INT_LITERAL:v    {: RESULT = new Nodo(v.toString(), TipoNodo.CONSTANTE); :}
    | FLOAT_LITERAL:v  {: RESULT = new Nodo(v.toString(), TipoNodo.CONSTANTE); :}
    | STRING_LITERAL:v {: RESULT = new Nodo(v.toString(), TipoNodo.CONSTANTE); :}
    | CHAR_LITERAL:v   {: RESULT = new Nodo(v.toString(), TipoNodo.CONSTANTE); :}
    | BOOL_LITERAL:v   {: RESULT = new Nodo(v.toString(), TipoNodo.CONSTANTE); :}
;
