/*
CURSO: Compiladores e Intérpretes
PROYECTO #2: Análisis Sintáctico
ESTUDIANTES: Sebastián Sandí Blanco y Melany Bustos Cerdas
ARCHIVO: parser.cup

OBJETIVO: Definir la gramática del lenguaje, realizar la estructura para el árbol sintáctico y la tabla de símbolos

ENTRADA: Especificaciones de terminales, no terminales, precedencias, nodos y la gramática del lenguaje

SALIDA: Clase java con constantes enteras que representan cada token y analizador sintáctico generado con CUP que construye el árbol
sintáctico y la tabla de símbolos.

RESTRICCIONES:
-La validación semántica se limita a errores básicos.

Código obtenido de la página oficial de Cup y adaptado para el proyecto
https://www2.cs.tum.edu/projects/cup/ */

package generados;
import java_cup.runtime.*;
import src.Nodo;
import java.util.HashMap;
import java.util.ArrayList;

parser code {:

    public boolean errorDetectado = false; //esto es para indicar si la estructura es válida o no

    public void errorEnGramatica(Symbol s) {
            errorDetectado = true;
            System.err.println("Error sintáctico: Token inesperado '" + s.value +
                               "' en la línea " + (s.left + 1) + ", columna " + (s.right + 1));
    }

    public void imprimirTablaSimbolos() {
        action_obj.imprimirTablaSimbolos();
    }
:};

action code {:
    HashMap<String, ArrayList<String>> tablaSimbolos = new HashMap<>();
    String scopeActual = "GLOBAL";

    {
        tablaSimbolos.put("GLOBAL", new ArrayList<>());
    }

    void agregarSimbolo(String nombre, String tipo) {
        ArrayList<String> tabla = tablaSimbolos.get(scopeActual);
        tabla.add(nombre + ":" + tipo + ":" + scopeActual);
    }


    public void imprimirTablaSimbolos() {
        for (String scope : tablaSimbolos.keySet()) {
            System.out.println("\nTabla de símbolos: " + scope);
            for (String s : tablaSimbolos.get(scope)) {
                System.out.println("  " + s);
            }
        }
    }
:}

/* Palabras reservadas */
terminal String WORLD;     // world
terminal String LOCAL;     // local
terminal String GIFT;      // gift
terminal String RETURN;    // return
terminal String BREAK;     // break

terminal String DECIDE;    // decide
terminal String OF;        // of
terminal String ELSE;      // else
terminal String END;       // end
terminal String LOOP;      // loop
terminal String EXIT;      // exit
terminal String WHEN;      // when
terminal String FOR;       // for

terminal String SHOW;      // show
terminal String GET;       // get
terminal String NAVIDAD;   // navidad (main)

/* Tipos de datos */
terminal String INT;       // int
terminal String FLOAT;     // float
terminal String BOOL;      // bool
terminal String CHAR;      // char
terminal String STRING;    // string
terminal String COAL;      // coal (tipo del main)

/* Operadores */
terminal String PLUS;      // +
terminal String MINUS;     // -
terminal String MULT;      // *
terminal String DIV;       // /
terminal String DIVENT;    // //
terminal String MOD;       // %
terminal String ELEV;      // ^
terminal String UMINUS;

terminal String INC;       // ++
terminal String DEC;       // --

terminal String LOWTHAN;        // <
terminal String LOWEQ;        // <=
terminal String GTHAN;        // >
terminal String GEQ;        // >=
terminal String EQ;        // ==
terminal String NEQ;        // !=

terminal String AND;       // @
terminal String OR;        // ~
terminal String NOT;       // Σ
terminal String ARROW;

/* Caracteres del lenguaje */
terminal String ASSIGN;    // =
terminal String LBRACE;    // ¡
terminal String RBRACE;    // !
terminal String LPAREN;    // ¿
terminal String RPAREN;    // ?
terminal String LBRACKET; // [
terminal String RBRACKET; // ]
terminal String COMMA;     // ,
terminal String ENDL;      // endl

/* Literales */
terminal Integer   INT_LITERAL;
terminal Double    FLOAT_LITERAL;
terminal String    STRING_LITERAL;
terminal Character CHAR_LITERAL;
terminal Boolean   BOOL_LITERAL;

/* Identificador */
terminal String ID; // nombres de variables y funciones

/* No terminales con tipos definidos */
non terminal Nodo programa, declaracionesGlobales, declaracionGlobal, listaFunciones, funcion, funcionMain, parametros, listaParametros, bloque, listaSentencias, 
sentencia, declaracionLocal, declaracionArreglo, arregloAsignacion, listaFilas, fila, listaValores, valoresArreglo, asignacion, sentenciaMostrar, sentenciaLeer, 
sentenciaReturn, sentenciaBreak, sentenciaDecide, casosDecide, casoDecide, casoElse, sentenciaLoop, salidaLoop, sentenciaFor, forIniciar, forActualizar, 
llamadaFuncion, argumentos, listaArgumentos, expresion, expresionLogica, terminoLogico, factorLogico, expresionRelacional, expresionAritmetica, termino, factor, 
unario, primario, literal, declaracion, declaracionVariable;
non terminal String tipo, operadorRelacional;

/* Precedencias */
precedence left OR;
precedence left AND;
precedence right NOT;
precedence left EQ, NEQ, LOWTHAN, LOWEQ, GTHAN, GEQ;
precedence left PLUS, MINUS;
precedence left MULT, DIV, DIVENT, MOD;
precedence right ELEV;
precedence right UMINUS;

start with programa;

programa ::= declaracionesGlobales:dg listaFunciones:lf funcionMain:m
    {:
        Nodo raiz = new Nodo("PROGRAMA");
        if(dg != null) raiz.agregarHijo(dg);
        if(lf != null) raiz.agregarHijo(lf);
        if(m != null) raiz.agregarHijo(m);

        if(parser.errorDetectado) {
                    System.out.println("\n[ERROR] Estructura NO válida según la gramática.");
                } else {
                    System.out.println("\n[ÉXITO] Estructura válida según la gramática.");
                }
        RESULT = raiz;
    :}
;

declaracionesGlobales ::= declaracionesGlobales:dsG declaracionGlobal:dG
    {:
        dsG.agregarHijo(dG);
        RESULT = dsG;
    :}
    | /* caso base vacío */
    {: RESULT = new Nodo("LISTA DECLARACIONES GLOBALES"); :}
;


declaracionGlobal ::= WORLD tipo:t ID:i ENDL {:
  scopeActual = "GLOBAL";
  agregarSimbolo(i, t);
  Nodo declaracionG = new Nodo("Declaración global: " + t + " " + i);
  RESULT = declaracionG;

:}
		    | WORLD tipo:t ID:i ASSIGN expresion ENDL {:
        scopeActual = "GLOBAL";
        agregarSimbolo(i, t);
		    Nodo declaracionG = new Nodo("Declaración global con asignación: " + t + " " + i);
		    RESULT = declaracionG;
        :}
;

tipo ::= INT     {: RESULT = "int"; :}
       | FLOAT   {: RESULT = "float"; :}
       | BOOL    {: RESULT = "bool"; :}
       | CHAR    {: RESULT = "char"; :}
       | STRING  {: RESULT = "string"; :}
;


listaFunciones ::= listaFunciones:lf funcion:f
    {:
        lf.agregarHijo(f);
        RESULT = lf;
    :}
    | /* caso base vacío */
    {: RESULT = new Nodo("LISTA FUNCIONES"); :}
;

funcion ::= GIFT tipo:t ID:id
    {:
        scopeActual = "GLOBAL";
        agregarSimbolo(id, t + " (función)");
        scopeActual = id;
        tablaSimbolos.put(scopeActual, new ArrayList<>());
    :}
    LPAREN parametros:p RPAREN bloque:b
    {:
        Nodo funcion = new Nodo("Función: " + id);
        funcion.agregarHijo(p);
        funcion.agregarHijo(b);
        scopeActual = "GLOBAL"; // Regresa al ámbito global
        RESULT = funcion;
    :}
    | error RBRACE {:
            parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR EN ESTRUCTURA DE FUNCIÓN <<<");
          :}
;

funcionMain ::= COAL NAVIDAD LPAREN RPAREN
    {:
        scopeActual = "GLOBAL";
        agregarSimbolo("navidad", "coal (función)");
        scopeActual = "navidad";
        tablaSimbolos.put(scopeActual, new ArrayList<>());
    :}
    bloque:b
    {:
        Nodo funcionMain = new Nodo("Función Main");
        funcionMain.agregarHijo(b);
        scopeActual = "GLOBAL";
        RESULT = funcionMain;
    :}
    | error {:
            //parser.errorDetectado = true;
            RESULT = new Nodo(">>> ERROR CRÍTICO EN FUNCIÓN MAIN <<<");
        :};


parametros ::= {:
    RESULT = new Nodo("Lista de parámetros vacía");
:}
| listaParametros:lp {:
    RESULT = lp;
:};

listaParametros ::= tipo:t ID:id {:
    agregarSimbolo(id, t);
    Nodo contenedor = new Nodo("Parámetros");
    contenedor.agregarHijo(new Nodo("Parámetro: " + id));
    RESULT = contenedor;
:}
| listaParametros:lp COMMA tipo:t ID:id {:
    agregarSimbolo(id, t);
    lp.agregarHijo(new Nodo("Parámetro: " + id));
    RESULT = lp;
:};


bloque ::= LBRACE listaSentencias:ls RBRACE {:
    Nodo bloque = new Nodo("Bloque");
    bloque.agregarHijo(ls);
    RESULT = bloque;
:};

listaSentencias ::= listaSentencias:ls sentencia:s
    {:
        ls.agregarHijo(s);
        RESULT = ls;
    :}
    | /* caso base vacío */
    {: RESULT = new Nodo("LISTA SENTENCIAS"); :}
;

sentencia ::= declaracionLocal:s    {: RESULT = s; :}
            | declaracionArreglo:s  {: RESULT = s; :}
            | asignacion:s          {: RESULT = s; :}
            | expresion:e ENDL      {:
                Nodo sent = new Nodo("Sentencia Expresión");
                sent.agregarHijo(e);
                RESULT = sent;
              :}
            | error ENDL
                          {:
                            System.err.println("Error sintáctico detectado. El parser se sincronizará en el siguiente 'endl'.");
                            Nodo errorNodo = new Nodo(">>> ERROR SINTÁCTICO <<<");
                            parser.errorDetectado = true;
                            RESULT = errorNodo;
                          :}
            | sentenciaMostrar:s    {: RESULT = s; :}
            | sentenciaLeer:s       {: RESULT = s; :}
            | sentenciaReturn:s     {: RESULT = s; :}
            | sentenciaBreak:s      {: RESULT = s; :}
            | sentenciaDecide:s     {: RESULT = s; :}
            | sentenciaLoop:s       {: RESULT = s; :}
            | sentenciaFor:s        {: RESULT = s; :}

;

declaracionLocal ::=
    LOCAL declaracion:d
    {:
        Nodo n = new Nodo("Declaración local");
        n.agregarHijo(d);
        RESULT = n;
    :}
;

declaracion ::=
      declaracionVariable:dv
      {: RESULT = dv; :}
    | declaracionArreglo:da
      {: RESULT = da; :}
;

declaracionVariable ::=
      tipo:t ID:i ENDL
      {:
          agregarSimbolo(i, t);
          RESULT = new Nodo("Declaración de variable: " + t + " " + i);
      :}
    | tipo:t ID:i ASSIGN expresion:e ENDL
      {:
          agregarSimbolo(i, t);
          Nodo n = new Nodo("Declaración de variable con asignación: " + t + " " + i);
          n.agregarHijo(e);
          RESULT = n;
      :}
;

declaracionArreglo ::= tipo:t ID:i LBRACKET INT_LITERAL RBRACKET LBRACKET INT_LITERAL RBRACKET ENDL {:
                         agregarSimbolo(i, t + "[ ][ ]");
                        RESULT = new Nodo("Declaración arreglo bidimensional: " + i + " " + t + "[ ][ ]");
                    :}
                     | tipo:t ID:i LBRACKET INT_LITERAL RBRACKET LBRACKET INT_LITERAL RBRACKET ASSIGN arregloAsignacion:a ENDL {:
                        agregarSimbolo(i, t + "[ ][ ]");
                        Nodo n = new Nodo("Declaración de arreglo con asignación " + i + " " + t + "[ ][ ]");
                        n.agregarHijo(a);
                        RESULT = n;
                    :}
;

arregloAsignacion ::= LBRACE listaFilas:lf RBRACE {:
                        Nodo n = new Nodo("Valores Arreglo");
                        n.agregarHijo(lf);
                        RESULT = n;
                    :}
;

listaFilas ::= fila:f {:
                Nodo n = new Nodo("Lista de Filas");
                n.agregarHijo(f);
                RESULT = n;
              :}
             | listaFilas:lf fila:f {:
                lf.agregarHijo(f);
                RESULT = lf;
              :}
;

fila ::= LBRACE listaValores:lv RBRACE {:
            Nodo n = new Nodo("Fila");
            n.agregarHijo(lv);
            RESULT = n;
         :}
;

listaValores ::= valoresArreglo:v {:
                    Nodo n = new Nodo("Lista de Valores");
                    n.agregarHijo(v);
                    RESULT = n;
                 :}
               | listaValores:lv COMMA valoresArreglo:v {:
                    lv.agregarHijo(v);
                    RESULT = lv;
                 :}
;

valoresArreglo ::= INT_LITERAL  {: RESULT = new Nodo("Valor Entero"); :}
                 | CHAR_LITERAL {: RESULT = new Nodo("Valor Char"); :}
;

asignacion ::= ID ASSIGN expresion:e ENDL {:
                Nodo n = new Nodo("Asignación");
                n.agregarHijo(e);
                RESULT = n;
              :}
             | ID LBRACKET expresion:e1 RBRACKET ASSIGN expresion:e2 ENDL {:
                Nodo n = new Nodo("Asignación Arreglo 1D");
                n.agregarHijo(e1);
                n.agregarHijo(e2);
                RESULT = n;
              :}
             | ID LBRACKET expresion:e1 RBRACKET LBRACKET expresion:e2 RBRACKET ASSIGN expresion:e3 ENDL {:
                Nodo n = new Nodo("Asignación Arreglo 2D");
                n.agregarHijo(e1);
                n.agregarHijo(e2);
                n.agregarHijo(e3);
                RESULT = n;
              :}
;

sentenciaMostrar ::= SHOW listaArgumentos:la ENDL {:
                        Nodo n = new Nodo("Sentencia Show");
                        n.agregarHijo(la);
                        RESULT = n;
                    :}
;

sentenciaLeer ::= GET ID ENDL {: RESULT = new Nodo("Sentencia Get"); :}
;

sentenciaDecide ::= DECIDE OF casosDecide:cd casoElse:ce END DECIDE ENDL {:
                        Nodo n = new Nodo("Sentencia Decide");
                        n.agregarHijo(cd);
                        n.agregarHijo(ce);
                        RESULT = n;
                    :}
;

casosDecide ::= casoDecide:c {:
                    Nodo n = new Nodo("Casos Decide");
                    n.agregarHijo(c);
                    RESULT = n;
                :}
              | casosDecide:cd casoDecide:c {:
                    cd.agregarHijo(c);
                    RESULT = cd;
                :}
;

casoDecide ::= expresion:e ARROW bloque:b {:
                Nodo n = new Nodo("Caso");
                n.agregarHijo(e);
                n.agregarHijo(b);
                RESULT = n;
              :}
              |
              LPAREN error RPAREN ARROW bloque:b
                  {:
                      parser.errorDetectado = true;
                      Nodo n = new Nodo("CASO (ERROR EN CONDICIÓN)");
                      n.agregarHijo(b); // se rescata el cuerpo del bloque
                      RESULT = n;
                  :}
;

casoElse ::= {: RESULT = new Nodo("Sin caso Else"); :}
           | ELSE ARROW bloque:b {:
                Nodo n = new Nodo("Caso Else");
                n.agregarHijo(b);
                RESULT = n;
             :}
;

sentenciaLoop ::= LOOP listaSentencias:ls salidaLoop:sl END LOOP ENDL {:
                    Nodo n = new Nodo("Sentencia Loop");
                    n.agregarHijo(ls);
                    n.agregarHijo(sl);
                    RESULT = n;
                  :}
;

salidaLoop ::= EXIT WHEN expresion:e ENDL {:
                Nodo n = new Nodo("Salida Loop");
                n.agregarHijo(e);
                RESULT = n;
              :}
;

sentenciaFor ::= FOR LPAREN forIniciar:fi ENDL expresion:e ENDL forActualizar:fa RPAREN bloque:b {:
                    Nodo n = new Nodo("Sentencia For");
                    n.agregarHijo(fi);
                    n.agregarHijo(e);
                    n.agregarHijo(fa);
                    n.agregarHijo(b);
                    RESULT = n;
                 :}
;


forIniciar ::= tipo:t ID:i ASSIGN expresion:e
      {:
          agregarSimbolo(i, t);
          Nodo n = new Nodo("For Inicio");
          n.agregarHijo(e);
          RESULT = n;
      :}
    | ID ASSIGN expresion:e
      {:
          Nodo n = new Nodo("For Inicio");
          n.agregarHijo(e);
          RESULT = n;
      :}
;


forActualizar ::= tipo ID ASSIGN expresion:e
      {:
          Nodo n = new Nodo("For Actualización");
          n.agregarHijo(e);
          RESULT = n;
      :}
    | INC ID {: RESULT = new Nodo("Incremento"); :}
    | ID INC {: RESULT = new Nodo("Incremento"); :}
    | DEC ID {: RESULT = new Nodo("Decremento"); :}
    | ID DEC {: RESULT = new Nodo("Decremento"); :}
;


sentenciaReturn ::= RETURN expresion:e ENDL {:
                        Nodo n = new Nodo("Sentencia Return");
                        n.agregarHijo(e);
                        RESULT = n;
                    :}
;

sentenciaBreak ::= BREAK ENDL {: RESULT = new Nodo("Sentencia Break"); :}
;

llamadaFuncion ::= ID LPAREN argumentos:a RPAREN {:
                    Nodo n = new Nodo("Llamada a Función");
                    n.agregarHijo(a);
                    RESULT = n;
                  :}
;

argumentos ::= {: RESULT = new Nodo("Sin argumentos"); :}
             | listaArgumentos:la {: RESULT = la; :}
;

listaArgumentos ::= expresion:e {:
                        Nodo n = new Nodo("Lista de Argumentos");
                        n.agregarHijo(e);
                        RESULT = n;
                    :}
                  | listaArgumentos:la COMMA expresion:e {:
                        la.agregarHijo(e);
                        RESULT = la;
                    :}
;

expresion ::= expresionLogica:e {: RESULT = e; :}
;

expresionLogica ::= expresionLogica:e OR terminoLogico:t {:
                        Nodo n = new Nodo("Expresión Lógica (OR)");
                        n.agregarHijo(e);
                        n.agregarHijo(t);
                        RESULT = n;
                    :}
                  | terminoLogico:t {: RESULT = t; :}
;

terminoLogico ::= terminoLogico:t AND factorLogico:f {:
                    Nodo n = new Nodo("Término Lógico (AND)");
                    n.agregarHijo(t);
                    n.agregarHijo(f);
                    RESULT = n;
                  :}
                | factorLogico:f {: RESULT = f; :}
;

factorLogico ::= NOT factorLogico:f {:
                    Nodo n = new Nodo("Negación Lógica");
                    n.agregarHijo(f);
                    RESULT = n;
                 :}
               | expresionRelacional:e {: RESULT = e; :}
;

expresionRelacional ::= expresionAritmetica:e1 operadorRelacional:op expresionAritmetica:e2 {:
                            Nodo n = new Nodo("Expresión Relacional");
                            n.agregarHijo(e1);
                            n.agregarHijo(new Nodo("operador relacional"));
                            n.agregarHijo(e2);
                            RESULT = n;
                        :}
                      | expresionAritmetica:e {: RESULT = e; :}
;

operadorRelacional ::= LOWTHAN {: RESULT = "<"; :}
                     | LOWEQ   {: RESULT = "<="; :}
                     | GTHAN   {: RESULT = ">"; :}
                     | GEQ     {: RESULT = ">="; :}
                     | EQ      {: RESULT = "=="; :}
                     | NEQ     {: RESULT = "!="; :}
;

expresionAritmetica ::= expresionAritmetica:e PLUS termino:t {:
                            Nodo n = new Nodo("Suma");
                            n.agregarHijo(e);
                            n.agregarHijo(t);
                            RESULT = n;
                        :}
                      | expresionAritmetica:e MINUS termino:t {:
                            Nodo n = new Nodo("Resta");
                            n.agregarHijo(e);
                            n.agregarHijo(t);
                            RESULT = n;
                        :}
                      | termino:t {: RESULT = t; :}
;

termino ::= termino:t MULT factor:f {:
                Nodo n = new Nodo("Multiplicación");
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t DIV factor:f {:
                Nodo n = new Nodo("División");
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t DIVENT factor:f {:
                Nodo n = new Nodo("División Entera");
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | termino:t MOD factor:f {:
                Nodo n = new Nodo("Módulo");
                n.agregarHijo(t);
                n.agregarHijo(f);
                RESULT = n;
            :}
          | factor:f {: RESULT = f; :}
;

factor ::= factor:f ELEV unario:u {:
            Nodo n = new Nodo("Potencia");
            n.agregarHijo(f);
            n.agregarHijo(u);
            RESULT = n;
          :}
         | unario:u {: RESULT = u; :}
;

unario ::= MINUS unario:u {:
            Nodo n = new Nodo("Menos Unario");
            n.agregarHijo(u);
            RESULT = n;
          :} %prec UMINUS
         | INC ID {: RESULT = new Nodo("Incremento"); :}
         | DEC ID {: RESULT = new Nodo("Decremento"); :}
         | primario:p {: RESULT = p; :}
;

primario ::= ID {: RESULT = new Nodo("Identificador"); :}
           | literal:l {: RESULT = l; :}
           | llamadaFuncion:lf {: RESULT = lf; :}
           | ID LBRACKET expresion:e1 RBRACKET LBRACKET expresion:e2 RBRACKET {:
                Nodo n = new Nodo("Acceso Arreglo");
                n.agregarHijo(e1);
                n.agregarHijo(e2);
                RESULT = n;
             :}
           | LPAREN expresion:e RPAREN {: RESULT = e; :}
;

literal ::= INT_LITERAL    {: RESULT = new Nodo("Literal Entero"); :}
          | FLOAT_LITERAL  {: RESULT = new Nodo("Literal Flotante"); :}
          | STRING_LITERAL {: RESULT = new Nodo("Literal String"); :}
          | CHAR_LITERAL   {: RESULT = new Nodo("Literal Char"); :}
          | BOOL_LITERAL   {: RESULT = new Nodo("Literal Bool"); :}
;
