/*
CURSO: Compiladores e Intérpretes
PROYECTO #1: Análisis Léxico
ESTUDIANTES: Sebastián Sandí Blanco y Melany Bustos Cerdas
ARCHIVO: parser.cup

OBJETIVO: Definir la gramática del lenguaje
ENTRADA: Especificaciones de terminales y no terminales
SALIDA: Clase java con constantes enteras que representan cada token
RESTRICCIONES:
- Solo se definen los terminales en esta fase del proyecto, no producciones
- Incluye una producción mínima para permitir la generación de código

Código obtenido de la página oficial de Cup y adaptado para el proyecto
https://www2.cs.tum.edu/projects/cup/ */

package generados;
import java_cup.runtime.*;
import src.Nodo;

/* Palabras reservadas */
terminal String WORLD;     // world
terminal String LOCAL;     // local
terminal String GIFT;      // gift
terminal String RETURN;    // return
terminal String BREAK;     // break

terminal String DECIDE;    // decide
terminal String OF;        // of
terminal String ELSE;      // else
terminal String END;       // end
terminal String LOOP;      // loop
terminal String EXIT;      // exit
terminal String WHEN;      // when
terminal String FOR;       // for

terminal String SHOW;      // show
terminal String GET;       // get
terminal String NAVIDAD;   // navidad (main)

/* Tipos de datos */
terminal String INT;       // int
terminal String FLOAT;     // float
terminal String BOOL;      // bool
terminal String CHAR;      // char
terminal String STRING;    // string
terminal String COAL;      // coal (tipo del main)

/* Operadores */
terminal String PLUS;      // +
terminal String MINUS;     // -
terminal String MULT;      // *
terminal String DIV;       // /
terminal String DIVENT;    // //
terminal String MOD;       // %
terminal String ELEV;      // ^

terminal String INC;       // ++
terminal String DEC;       // --

terminal String LOWTHAN;        // <
terminal String LOWEQ;        // <=
terminal String GTHAN;        // >
terminal String GEQ;        // >=
terminal String EQ;        // ==
terminal String NEQ;        // !=

terminal String AND;       // @
terminal String OR;        // ~
terminal String NOT;       // Σ
terminal String ARROW;

/* Caracteres del lenguaje */
terminal String ASSIGN;    // =
terminal String LBRACE;    // ¡
terminal String RBRACE;    // !
terminal String LPAREN;    // ¿
terminal String RPAREN;    // ?
terminal String LBRACKET; // [
terminal String RBRACKET; // ]
terminal String COMMA;     // ,
terminal String ENDL;      // endl

/* Literales */
terminal Integer   INT_LITERAL;     
terminal Double    FLOAT_LITERAL;   
terminal String    STRING_LITERAL;  
terminal Character CHAR_LITERAL;  
terminal Boolean   BOOL_LITERAL;   

/* Identificador */
terminal String ID; // nombres de variables y funciones

/* No terminales */
non terminal Nodo programa, declaracionGlobal,funcionNavidad, tipoArreglo, listaFunciones, funcion, funcionMain, parametros, listaParametros, bloque, listaSentencias, sentencia, declaracionLocal, declaracionArreglo, asignacion, sentenciaMostrar, sentenciaLeer, sentenciaReturn, sentenciaBreak, sentenciaDecide, casosDecide, casoDecide, casoElse, sentenciaLoop, salidaLoop, sentenciaFor, forIniciar, forActualizar, llamadaFuncion, argumentos, listaArgumentos, expresion, expresionLogica, terminoLogico, factorLogico, expresionRelacional, operadorRelacional, expresionAritmetica, termino, factor, unario, primario, literal;

programa ::= declaracionesGlobales:dg listaFunciones:lf funcionMain:m
    {:
        Nodo raiz = new Nodo("PROGRAMA");
        raiz.agregarHijo(dg);
        raiz.agregarHijo(lf);
        raiz.agregarHijo(m);
        RESULT = raiz;
    :}


declaracionesGlobales ::= /* vacío */ | declaracionesGlobales declaracionGlobal ;


declaracionGlobal ::= WORLD tipo ID ENDL | WORLD tipo ID ASSIGN expresion ENDL ;


tipo ::= INT | FLOAT | BOOL | CHAR | STRING ;

tipoArreglo ::= INT | CHAR ;


listaFunciones ::= /* vacío */ | listaFunciones funcion ;


funcion ::= GIFT tipo ID LPAREN parametros RPAREN bloque ;


parametros ::= /* vacío */ | listaParametros ;


listaParametros ::= tipo ID | listaParametros COMMA tipo ID ;


funcionMain ::= COAL NAVIDAD LPAREN RPAREN bloque ;


bloque ::= LBRACE listaSentencias RBRACE ;

listaSentencias ::= /* vacío */ | listaSentencias sentencia ;

sentencia ::= declaracionLocal | declaracionArreglo | asignacion | expresion ENDL | sentenciaMostrar | sentenciaLeer | sentenciaReturn | sentenciaBreak | sentenciaDecide | sentenciaLoop | sentenciaFor ;

declaracionLocal ::= LOCAL tipo ID ENDL | LOCAL tipo ID ASSIGN expresion ENDL ;


declaracionArreglo ::= tipoArreglo ID LBRACKET INT_LITERAL RBRACKET LBRACKET INT_LITERAL RBRACKET ENDL ;

asignacion ::= ID ASSIGN expresion ENDL | ID LBRACKET expresion RBRACKET ASSIGN expresion ENDL | ID LBRACKET expresion RBRACKET LBRACKET expresion RBRACKET ASSIGN expresion ENDL ;

sentenciaMostrar ::= SHOW listaArgumentos ENDL ;

sentenciaLeer ::= GET ID ENDL ;


sentenciaDecide ::= DECIDE OF casosDecide casoElse END DECIDE ENDL ;

casoDecide ::= casoDecide | casosDecide casoDecide ;

casoDecide ::= expresion ARROW bloque ;

casoElse ::= /* vacío */ | ELSE ARROW bloque ;

sentenciaLoop ::= LOOP lista_sentencias salida_loop END LOOP ENDL ;

salidaLoop ::= EXIT WHEN expresion ENDL ;


sentenciaFor ::= FOR LPAREN forIniciar ENDL expresion ENDL forActualizar RPAREN bloque ;

forIniciar ::= ID ASSIGN expresion ;

forActualizar ::= ID ASSIGN expresion ;


sentenciaReturn ::= RETURN expresion ENDL ;

sentenciaBreak ::= BREAK ENDL ;


llamadaFuncion ::= ID LPAREN argumentos RPAREN ;

argumentos ::= /* vacío */ | listaArgumentos ;

listaArgumentos ::= expresion | listaArgumentos COMMA expresion ;


expresion ::= expresionLogica ;


expresionLogica ::= expresionLogica OR terminoLogico | terminoLogico ;


terminoLogico ::= terminoLogico AND factorLogico | factorLogico ;


factorLogico ::= NOT factorLogico | expresionRelacional ;


expresionRelacional ::= expresionAritmetica operadorRelacional expresionAritmetica | expresionAritmetica ;


operadorRelacional ::= LOWTHAN | LOWEQ | GTHAN | GEQ | EQ | NEQ ;


expresionAritmetica ::= expresionAritmetica PLUS termino | expresionAritmetica MINUS termino | termino ;


termino ::= termino MULT factor | termino DIV factor | termino DIVENT factor | termino MOD factor | factor ;


factor ::= factor ELEV unario | unario ;


unario ::= MINUS unario | INC ID | DEC ID | primario ;


primario ::= ID | literal | llamadaFuncion | ID LBRACKET expresion RBRACKET LBRACKET expresion RBRACKET | LPAREN expresion RPAREN ;


literal ::= INT_LITERAL | FLOAT_LITERAL | STRING_LITERAL | CHAR_LITERAL | BOOL_LITERAL ;


;
