
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package generados;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 13;
  public static final int SHOW = 15;
  public static final int STRING_LITERAL = 54;
  public static final int LBRACKET = 48;
  public static final int DIVENT = 28;
  public static final int MULT = 26;
  public static final int CHAR = 21;
  public static final int CHAR_LITERAL = 55;
  public static final int ELEV = 30;
  public static final int LPAREN = 46;
  public static final int LOWEQ = 34;
  public static final int INT = 18;
  public static final int FOR = 14;
  public static final int MINUS = 25;
  public static final int LOWTHAN = 33;
  public static final int RPAREN = 47;
  public static final int ENDL = 51;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int DECIDE = 7;
  public static final int COAL = 23;
  public static final int OR = 40;
  public static final int COMMA = 50;
  public static final int BOOL = 20;
  public static final int GET = 16;
  public static final int NAVIDAD = 17;
  public static final int INC = 31;
  public static final int DIV = 27;
  public static final int GEQ = 36;
  public static final int LOOP = 11;
  public static final int PLUS = 24;
  public static final int EXIT = 12;
  public static final int ASSIGN = 43;
  public static final int ID = 57;
  public static final int OF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int RBRACKET = 49;
  public static final int error = 1;
  public static final int MOD = 29;
  public static final int NEQ = 38;
  public static final int BREAK = 6;
  public static final int WORLD = 2;
  public static final int EQ = 37;
  public static final int ARROW = 42;
  public static final int GTHAN = 35;
  public static final int LBRACE = 44;
  public static final int ELSE = 9;
  public static final int FLOAT = 19;
  public static final int RBRACE = 45;
  public static final int END = 10;
  public static final int STRING = 22;
  public static final int LOCAL = 3;
  public static final int DEC = 32;
  public static final int FLOAT_LITERAL = 53;
  public static final int GIFT = 4;
  public static final int BOOL_LITERAL = 56;
  public static final int INT_LITERAL = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WORLD",
  "LOCAL",
  "GIFT",
  "RETURN",
  "BREAK",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "SHOW",
  "GET",
  "NAVIDAD",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "COAL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "DIVENT",
  "MOD",
  "ELEV",
  "INC",
  "DEC",
  "LOWTHAN",
  "LOWEQ",
  "GTHAN",
  "GEQ",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "ARROW",
  "ASSIGN",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "ENDL",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BOOL_LITERAL",
  "ID"
  };
}

